<?php
header('Content-Type: application/json');
header('Cache-Control: no-store');

function respond_json($code, $data) { http_response_code($code); echo json_encode($data); exit; }
function clean_text($value, $limit = 2000) { $value = trim(strip_tags((string)$value)); $value = preg_replace('/\s+/', ' ', $value); return function_exists('mb_substr') ? mb_substr($value, 0, $limit) : substr($value, 0, $limit); }
function normalize_url($url) { $url = trim((string)$url); if ($url === '') return ''; if (!preg_match('#^https?://#i', $url)) $url = 'https://' . $url; return $url; }
function is_public_host($host) { if (!$host || preg_match('/(^|\.)localhost$/i', $host)) return false; $records = @dns_get_record($host, DNS_A + DNS_AAAA); if (!$records || !is_array($records)) return true; foreach ($records as $record) { $ip = $record['ip'] ?? ($record['ipv6'] ?? null); if (!$ip) continue; if (!filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE)) return false; } return true; }
function fetch_url($url, $timeout = 15) { $ch = curl_init($url); curl_setopt_array($ch, [CURLOPT_RETURNTRANSFER => true, CURLOPT_FOLLOWLOCATION => true, CURLOPT_MAXREDIRS => 4, CURLOPT_CONNECTTIMEOUT => 8, CURLOPT_TIMEOUT => $timeout, CURLOPT_SSL_VERIFYPEER => true, CURLOPT_SSL_VERIFYHOST => 2, CURLOPT_USERAGENT => 'AxonWebsiteCheck/1.1 (+https://axon.com.sg)', CURLOPT_ENCODING => '', CURLOPT_HEADER => true]); $raw = curl_exec($ch); $err = curl_error($ch); $info = curl_getinfo($ch); curl_close($ch); if ($raw === false) return ['ok' => false, 'error' => $err ?: 'Unable to fetch URL', 'info' => $info, 'headers' => '', 'body' => '']; $headerSize = $info['header_size'] ?? 0; $headers = substr($raw, 0, $headerSize); $body = substr($raw, $headerSize); if (strlen($body) > 900000) $body = substr($body, 0, 900000); return ['ok' => true, 'error' => '', 'info' => $info, 'headers' => $headers, 'body' => $body]; }
function extract_match($pattern, $html) { if (preg_match($pattern, $html, $m)) return trim(html_entity_decode($m[1], ENT_QUOTES | ENT_HTML5, 'UTF-8')); return ''; }
function extract_all($pattern, $html, $limit = 8) { $items = []; if (preg_match_all($pattern, $html, $m)) { foreach ($m[1] as $value) { $value = clean_text(html_entity_decode($value, ENT_QUOTES | ENT_HTML5, 'UTF-8'), 180); if ($value !== '' && !in_array($value, $items, true)) $items[] = $value; if (count($items) >= $limit) break; } } return $items; }
function has_pattern($pattern, $text) { return preg_match($pattern, $text) === 1; }
function count_pattern($pattern, $text) { return preg_match_all($pattern, $text, $unused); }
function header_value($headers, $name) { $safe = preg_quote($name, '/'); if (preg_match_all('/^' . $safe . ':\s*(.*?)\s*$/im', $headers, $matches) && !empty($matches[1])) return trim(end($matches[1])); return ''; }
function bytes_to_label($bytes) { $bytes = (int)$bytes; if ($bytes <= 0) return 'Not detected'; if ($bytes >= 1048576) return round($bytes / 1048576, 2) . ' MB'; if ($bytes >= 1024) return round($bytes / 1024, 1) . ' KB'; return $bytes . ' bytes'; }
function abs_base($url) { $p = parse_url($url); return strtolower(($p['scheme'] ?? 'https') . '://' . ($p['host'] ?? '')); }
function detect_platform($html, $headers, $finalUrl) { $all = strtolower($html . "\n" . $headers . "\n" . $finalUrl); $checks = ['WordPress' => ['wp-content','wp-includes','wp-json','wordpress','woocommerce'], 'Wix' => ['wixstatic.com','static.parastorage.com','x-wix','wix.com/website'], 'Shopify' => ['cdn.shopify.com','shopify.theme','myshopify.com','shopify-section'], 'Squarespace' => ['squarespace.com','static1.squarespace.com','squarespace-cdn'], 'Webflow' => ['webflow.js','assets.website-files.com','data-wf-page'], 'WooCommerce' => ['woocommerce','wc-cart-fragments','wp-content/plugins/woocommerce'], 'Laravel/PHP app' => ['laravel_session','x-powered-by: php'], 'React / Next-style app' => ['__next_data__','/_next/static/','data-reactroot'], 'Elementor / WordPress builder' => ['elementor','elementor-pro'], 'Framer-style site' => ['framerusercontent.com','framer-motion']]; $found = []; foreach ($checks as $name => $needles) { foreach ($needles as $needle) { if (strpos($all, strtolower($needle)) !== false) { $found[$name] = true; break; } } } $detected = array_keys($found); if (empty($detected)) $detected[] = (preg_match('/\.php(\?|$)/i', parse_url($finalUrl, PHP_URL_PATH) ?: '') || stripos($headers, 'x-powered-by: php') !== false) ? 'Custom PHP / HTML website' : 'Custom or static HTML website'; $confidence = (count($detected) > 1 || $detected[0] !== 'Custom or static HTML website') ? 'medium-high' : 'low'; return ['detected' => $detected, 'confidence' => $confidence]; }
function check_url_exists($url) { $result = fetch_url($url, 10); $code = $result['info']['http_code'] ?? 0; return ['exists' => $result['ok'] && $code >= 200 && $code < 400, 'status' => $code, 'url' => $url]; }

$input = json_decode(file_get_contents('php://input'), true); if (!is_array($input)) $input = $_POST; if (!is_array($input) || empty($input)) $input = $_GET;
$url = normalize_url($input['url'] ?? ''); if ($url === '') respond_json(422, ['success' => false, 'message' => 'Please enter a website URL.']);
$parts = parse_url($url); if (!$parts || !in_array(strtolower($parts['scheme'] ?? ''), ['http','https'], true) || empty($parts['host'])) respond_json(422, ['success' => false, 'message' => 'Please enter a valid website URL.']);
$host = strtolower($parts['host']); if (!is_public_host($host)) respond_json(422, ['success' => false, 'message' => 'This website address cannot be checked.']);

$result = fetch_url($url); $info = $result['info']; $status = $info['http_code'] ?? 0; $finalUrl = $info['url'] ?? $url; $html = $result['body']; $headers = $result['headers'];
if (!$result['ok'] || $status < 200 || $status >= 500) { respond_json(200, ['success' => true, 'scan' => ['url' => $url, 'finalUrl' => $finalUrl, 'status' => $status, 'loads' => false, 'error' => $result['error'] ?: 'Website did not load successfully during the basic check.', 'platform' => ['detected' => ['Unable to determine'], 'confidence' => 'low']]]); }

$title = extract_match('/<title[^>]*>(.*?)<\/title>/is', $html);
$description = extract_match('/<meta[^>]+name=["\']description["\'][^>]+content=["\']([^"\']*)["\']/is', $html); if ($description === '') $description = extract_match('/<meta[^>]+content=["\']([^"\']*)["\'][^>]+name=["\']description["\']/is', $html);
$canonical = extract_match('/<link[^>]+rel=["\']canonical["\'][^>]+href=["\']([^"\']*)["\']/is', $html);
$robotsMeta = extract_match('/<meta[^>]+name=["\']robots["\'][^>]+content=["\']([^"\']*)["\']/is', $html);
$lang = extract_match('/<html[^>]+lang=["\']([^"\']*)["\']/is', $html);
$h1 = extract_all('/<h1[^>]*>(.*?)<\/h1>/is', $html, 5); $h2 = extract_all('/<h2[^>]*>(.*?)<\/h2>/is', $html, 8);
$viewport = has_pattern('/<meta[^>]+name=["\']viewport["\']/is', $html); $og = has_pattern('/<meta[^>]+property=["\']og:/is', $html); $twitter = has_pattern('/<meta[^>]+name=["\']twitter:/is', $html); $schema = has_pattern('/application\/ld\+json/i', $html);
$ga4 = has_pattern('/G-[A-Z0-9]{6,}/', $html); $gtm = has_pattern('/GTM-[A-Z0-9]+|GT-[A-Z0-9]+/', $html); $forms = count_pattern('/<form\b/i', $html); $mailto = has_pattern('/mailto:/i', $html); $whatsapp = has_pattern('/wa\.me|whatsapp/i', $html);
$imageCount = count_pattern('/<img\b/i', $html); $imagesMissingAlt = count_pattern('/<img\b(?![^>]*\balt=["\'][^"\']+)/i', $html); $scriptCount = count_pattern('/<script\b/i', $html); $externalScriptCount = count_pattern('/<script\b[^>]+src=["\']/i', $html); $stylesheetCount = count_pattern('/<link\b[^>]+rel=["\'][^"\']*stylesheet/i', $html); $styleBlockCount = count_pattern('/<style\b/i', $html); $cssCount = $styleBlockCount + $stylesheetCount; $iframeCount = count_pattern('/<iframe\b/i', $html); $videoCount = count_pattern('/<video\b|youtube\.com|vimeo\.com/i', $html);
$linkMatches = []; preg_match_all('/<a\b[^>]+href=["\']([^"\']+)["\']/i', $html, $linkMatches); $internal = 0; $external = 0; $base = abs_base($finalUrl); foreach ($linkMatches[1] ?? [] as $href) { if (preg_match('/^(mailto:|tel:|#)/i', $href)) continue; if (preg_match('#^https?://#i', $href)) { if (stripos($href, $base) === 0) $internal++; else $external++; } else $internal++; }
$cacheControl = header_value($headers, 'cache-control'); $serverHeader = header_value($headers, 'server'); $xPoweredBy = header_value($headers, 'x-powered-by'); $cfCache = header_value($headers, 'cf-cache-status'); $xCache = header_value($headers, 'x-cache'); $cdnClue = ($cfCache !== '' || stripos($serverHeader, 'cloudflare') !== false) ? 'Cloudflare clue detected' : (($xCache !== '') ? 'Cache/CDN header clue detected' : 'No obvious CDN/cache header clue detected');
$pageBytes = (int)($info['size_download'] ?? strlen($html)); $bodyBytes = strlen($html); $totalTimeMs = (int)round((float)($info['total_time'] ?? 0) * 1000); $ttfbMs = (int)round((float)($info['starttransfer_time'] ?? 0) * 1000); $redirectCount = (int)($info['redirect_count'] ?? 0);
$scheme = strtolower($parts['scheme']); $root = $scheme . '://' . $host; $robots = check_url_exists($root . '/robots.txt'); $sitemap = check_url_exists($root . '/sitemap.xml'); $llms = check_url_exists($root . '/llms.txt'); if (!$sitemap['exists'] && $robots['exists']) { $robotsBody = fetch_url($root . '/robots.txt', 8)['body'] ?? ''; if (preg_match('/^\s*Sitemap:\s*(\S+)/im', $robotsBody, $m)) $sitemap = check_url_exists(trim($m[1])); }
$platform = detect_platform($html, $headers, $finalUrl); $visibleText = clean_text(preg_replace('/<script\b[^>]*>.*?<\/script>|<style\b[^>]*>.*?<\/style>/is', ' ', $html), 600);
$scan = ['url' => $url, 'finalUrl' => $finalUrl, 'status' => $status, 'loads' => $status >= 200 && $status < 400, 'https' => stripos($finalUrl, 'https://') === 0, 'redirected' => $finalUrl !== $url, 'title' => clean_text($title, 220), 'metaDescription' => clean_text($description, 320), 'canonical' => clean_text($canonical, 300), 'robotsMeta' => clean_text($robotsMeta, 160), 'language' => clean_text($lang, 40), 'h1' => $h1, 'h2' => $h2, 'viewport' => $viewport, 'openGraph' => $og, 'twitterCard' => $twitter, 'schema' => $schema, 'ga4Detected' => $ga4, 'googleTagDetected' => $gtm, 'formCount' => (int)$forms, 'mailtoDetected' => $mailto, 'whatsappDetected' => $whatsapp, 'robots' => $robots, 'sitemap' => $sitemap, 'llms' => $llms, 'platform' => $platform, 'performance' => ['totalTimeMs' => $totalTimeMs, 'ttfbMs' => $ttfbMs, 'redirectCount' => $redirectCount, 'pageBytes' => $pageBytes, 'pageSizeLabel' => bytes_to_label($pageBytes), 'bodyBytes' => $bodyBytes, 'bodySizeLabel' => bytes_to_label($bodyBytes), 'imageCount' => (int)$imageCount, 'imagesMissingAlt' => (int)$imagesMissingAlt, 'scriptCount' => (int)$scriptCount, 'externalScriptCount' => (int)$externalScriptCount, 'cssCount' => (int)$cssCount, 'stylesheetCount' => (int)$stylesheetCount, 'styleBlockCount' => (int)$styleBlockCount, 'iframeCount' => (int)$iframeCount, 'videoEmbedCount' => (int)$videoCount, 'internalLinkCount' => (int)$internal, 'externalLinkCount' => (int)$external, 'cacheControl' => clean_text($cacheControl, 240), 'serverHeader' => clean_text($serverHeader, 160), 'xPoweredBy' => clean_text($xPoweredBy, 160), 'cfCacheStatus' => clean_text($cfCache, 80), 'xCache' => clean_text($xCache, 120), 'cdnClue' => $cdnClue], 'contentLength' => strlen($html), 'textSample' => $visibleText];
respond_json(200, ['success' => true, 'scan' => $scan]);
