ding wp-content/uploads/2018/09/CW-ME1-1024x768.jpg
FAILED: https://web.archive.org/web/20240820002324if_/https://www.coolworldaircon.com.sg/wp-content/uploads/2018/09/CW-ME1-1024x768.jpg
The remote name could not be resolved: 'web.archive.org'
Downloading wp-content/uploads/2018/06/aircon-servicing-1024x121-768x91.png
FAILED: https://web.archive.org/web/20240820013651if_/https://www.coolworldaircon.com.sg/wp-content/uploads/2018/06/aircon-servicing-1024x121-768x91.png
The remote name could not be resolved: 'web.archive.org'
Downloading wp-content/uploads/2018/08/BUYING-AN-AIR-CONDITION-UNIT-768x512.jpg
FAILED: https://web.archive.org/web/20240820021838if_/https://www.coolworldaircon.com.sg/wp-content/uploads/2018/08/BUYING-AN-AIR-CONDITION-UNIT-768x512.jpg
The remote name could not be resolved: 'web.archive.org'
Downloading wp-content/uploads/2018/09/Cool-World-Aircon-logo-150x45.png
FAILED: https://web.archive.org/web/20240820035528if_/https://www.coolworldaircon.com.sg/wp-content/uploads/2018/09/Cool-World-Aircon-logo-150x45.png
The remote name could not be resolved: 'web.archive.org'
Downloading wp-content/uploads/2018/08/1-150x99.png
FAILED: https://web.archive.org/web/20240820040210if_/https://www.coolworldaircon.com.sg/wp-content/uploads/2018/08/1-150x99.png
The remote name could not be resolved: 'web.archive.org'
Downloading wp-content/uploads/2018/06/Aircon-Installation-25-1024x576.jpg
FAILED: https://web.archive.org/web/20240820065716if_/https://www.coolworldaircon.com.sg/wp-content/uploads/2018/06/Aircon-Installation-25-1024x576.jpg
The remote name could not be resolved: 'web.archive.org'
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Write-Host "Completed."
Completed.
PS C:\WINDOWS\system32> (Get-ChildItem $Root -Recurse -File).Count
